### ISSUE TITLE
能否支持docker部署呢？上传能否可以显示进度条呢？

### ISSUE THREAD

**Issue by waleraye** [llaurora/netease-cloud-uploader#2]
非常感谢您的开发，ios很有用，windows上官方的应用会校验版权的，使用这个可以绕过的，
希望可以支持下这两个功能
- docker部署比较方便，也不用管npm依赖了
- 上传的时候点击保存只是在转圈，如果可以有一个相关的进度条应该会更加，可以看到上传了多少，
- 另外不知道是bug还是什么，我一次上传了两首flac的歌曲，文件比较大，第二首上传失败了，单次上传一首都是可以的
- 还要个问题是登录之后如果刷新网页的话登录状态会掉，我是在本地用npm运行的，访问的是locahost

**Comment by llaurora** [comment]
@waleraye 感谢您的建议
 
* 目前已支持登录状态保持；
* 因项目API调用基于 [NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)，暂时还拿不到进度数据；
* 大文件上传优化和docker部署我后面些再整吧；
